import { ApolloQueryResult } from '@apollo/client';
import type { InferGetStaticPropsType } from 'next';
import Head from 'next/head';

import apolloClient from '@/lib/graphql';

import { PageHero } from '@/components/PageHero';

import { GetPageHeroDocument, GetPageHeroQuery } from '../misuku/api';

export const getStaticProps = async () => {
  const response: ApolloQueryResult<GetPageHeroQuery> = await apolloClient.query<GetPageHeroQuery>({
    query: GetPageHeroDocument,
  });

  return {
    props: {
      data: response.data.hero,
    },
  };
};

const Home = ({ data }: InferGetStaticPropsType<typeof getStaticProps>) => {
  if (!data) {
    return;
  }
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageHero data={data} />
    </div>
  );
};

export default Home;
